"""
CooledAI Configuration - Facility topology and settings.

Plug-and-play: update topology_map.yaml for any new facility.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml
except ImportError:
    yaml = None

# Default path relative to project root
_CONFIG_DIR = Path(__file__).resolve().parent
TOPOLOGY_MAP_PATH = _CONFIG_DIR / "topology_map.yaml"

_cached_topology: Optional[Dict[str, Any]] = None


def load_topology_map(path: Optional[Path] = None) -> Dict[str, Any]:
    """
    Load topology map from YAML. Cached for performance.

    Returns:
        Dict with node_to_rack, rack_to_cooling, gpu_partitions (optional).
    """
    global _cached_topology
    if _cached_topology is not None:
        return _cached_topology

    p = path or TOPOLOGY_MAP_PATH
    if not p.exists():
        return {}

    if yaml is None:
        return {}

    try:
        with open(p, "r") as f:
            _cached_topology = yaml.safe_load(f) or {}
        return _cached_topology
    except Exception:
        return {}


def get_node_to_rack_map(path: Optional[Path] = None) -> Dict[str, str]:
    """Get node_name -> rack_id mapping."""
    topo = load_topology_map(path)
    return topo.get("node_to_rack") or {}


def resolve_node_to_rack(node_id: str, path: Optional[Path] = None) -> Optional[str]:
    """Resolve node_id to rack_id. Uses topology map, then pattern fallback."""
    node_to_rack = get_node_to_rack_map(path)
    if node_id in node_to_rack:
        return node_to_rack[node_id]
    # Heuristic: "node-rack-01" -> "rack_01"
    if "rack" in node_id.lower():
        parts = node_id.lower().replace("_", "-").split("-")
        for i, p in enumerate(parts):
            if p == "rack" and i + 1 < len(parts):
                try:
                    n = int(parts[i + 1])
                    return f"rack_{n:02d}"
                except ValueError:
                    return f"rack_{parts[i + 1]}"
    return None


def get_rack_to_cooling_map(path: Optional[Path] = None) -> Dict[str, List[str]]:
    """Get rack_id -> [cooling_unit_ids] mapping."""
    topo = load_topology_map(path)
    raw = topo.get("rack_to_cooling") or {}
    # Normalize: support both list and dict formats
    out: Dict[str, List[str]] = {}
    for rack_id, units in raw.items():
        if isinstance(units, list):
            out[rack_id] = [u if isinstance(u, str) else str(u) for u in units]
        else:
            out[rack_id] = [str(units)]
    return out


def get_gpu_partitions(path: Optional[Path] = None) -> List[str]:
    """Get GPU partition names for Slurm (optional override)."""
    topo = load_topology_map(path)
    return topo.get("gpu_partitions") or ["gpu", "a100", "h100", "a100x", "gpu-t4"]


def get_rack_thermal_mass(path: Optional[Path] = None) -> Dict[str, float]:
    """Get rack_id -> thermal_mass (J/K) mapping. Default 150000 if not in map."""
    topo = load_topology_map(path)
    raw = topo.get("rack_thermal_mass") or {}
    return {k: float(v) for k, v in raw.items()}


def clear_topology_cache() -> None:
    """Clear cached topology (e.g. after config reload)."""
    global _cached_topology
    _cached_topology = None


def load_influence_map(path: Optional[Path] = None) -> Optional["InfluenceMap"]:
    """
    Load InfluenceMap from YAML (e.g. generated by discovery agent thermal ping).
    Returns None if file does not exist or parsing fails.
    """
    from core.ingestion.influence_map import InfluenceMap

    p = path or _CONFIG_DIR / "influence_map.yaml"
    if not p.exists() or yaml is None:
        return None
    try:
        with open(p, "r") as f:
            data = yaml.safe_load(f) or {}
        return InfluenceMap.from_dict(data)
    except Exception:
        return None
