#!/usr/bin/env bash
# =============================================================================
# CooledAI Simulator - Environment Setup Script
# =============================================================================
# Generates .env (backend) and frontend/.env.local with all required keys.
# Run once after cloning, then fill in real values.
#
# Usage:
#   chmod +x setup_env.sh
#   ./setup_env.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_ENV="$SCRIPT_DIR/.env"
FRONTEND_ENV="$SCRIPT_DIR/frontend/.env.local"

# --- Generate a random 32-character hex string for API keys ---
generate_key() {
    if command -v openssl &>/dev/null; then
        openssl rand -hex 16
    elif command -v python3 &>/dev/null; then
        python3 -c "import secrets; print(secrets.token_hex(16))"
    else
        # Fallback: urandom
        head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'
        echo
    fi
}

echo "=================================================="
echo "  CooledAI Environment Setup"
echo "=================================================="
echo ""

# --- Backend .env ---
if [ -f "$BACKEND_ENV" ]; then
    echo "[SKIP] $BACKEND_ENV already exists."
    echo "       Delete it and re-run to regenerate, or edit manually."
else
    API_KEY=$(generate_key)
    ADMIN_KEY=$(generate_key)

    cat > "$BACKEND_ENV" << ENVEOF
# =============================================================================
# CooledAI Simulator - Backend Environment Variables
# =============================================================================
# Generated by setup_env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# NEVER commit this file. It is in .gitignore.
# =============================================================================

# --- Environment Mode ---
# Set to "dev" for local development (enables localhost CORS, disables HSTS)
# Set to "production" for deployment (strict CORS, HSTS enabled)
COOLEDAI_ENV=dev

# --- Server ---
PORT=8000
# HOST=127.0.0.1 for local dev (default), 0.0.0.0 for containers
HOST=127.0.0.1

# --- API Authentication ---
# Required for control endpoints (POST /optimize, /state, /apply, /ingest/*, /api/v1/telemetry)
# The gateway and any client must send this in the X-API-Key header.
COOLEDAI_API_KEY=${API_KEY}

# Required for admin endpoints (/admin/*, /shadow POST, /test-email, /discovery/clear)
# Falls back to COOLEDAI_API_KEY if not set separately.
COOLEDAI_ADMIN_KEY=${ADMIN_KEY}

# --- CORS (optional override) ---
# Comma-separated origins. If empty, defaults to https://cooledai.com + https://www.cooledai.com
# In dev mode (COOLEDAI_ENV=dev), localhost:3000 and 127.0.0.1:3000 are added automatically.
# CORS_ORIGINS=https://cooledai.com,https://www.cooledai.com

# --- Financial & Utility Rates ---
COOLEDAI_UTILITY_RATE=0.12
COOLEDAI_CO2_KG_PER_KWH=0.4
COOLEDAI_REBATE_PER_KWH=0.05
COOLEDAI_PROJECTED_PUE_IMPROVEMENT_PCT=12

# --- Shadow Mode ---
COOLEDAI_MISSED_OPPORTUNITY_THRESHOLD_USD=10

# --- AI/LLM (Briefing Agent, Discovery Agent) ---
# At least one required for LLM features. Leave blank to disable.
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
COOLEDAI_LLM_MODEL=gpt-4o-mini

# --- Email (Lead Capture, Beta Signup) ---
# Get API key from https://resend.com
RESEND_API_KEY=
LEAD_EMAIL_FROM=CooledAI <onboarding@resend.dev>
LEAD_EMAIL_TO=dennis@cooledai.com

# --- Gateway (Edge Agent) ---
# Set these when running gateway/main.py on the edge device.
# The gateway authenticates to the backend using COOLEDAI_API_KEY above.
COOLEDAI_BACKEND_URL=https://proactive-creativity-production.up.railway.app
COOLEDAI_AGENT_ID=default
HEARTBEAT_INTERVAL_SEC=10
COOLEDAI_CLOUD_LOSS_TIMEOUT_SEC=30
CONTROL_MODE=SHADOW

# --- Watchdog Sidecar ---
# The sidecar hits /health (unauthenticated) to check API liveness.
# If the API is unreachable for COOLEDAI_API_TIMEOUT seconds, it forces
# fans to fail-safe via Redfish.
COOLEDAI_API_URL=https://proactive-creativity-production.up.railway.app
COOLEDAI_API_TIMEOUT=30
COOLEDAI_REDFISH_URLS=
COOLEDAI_REDFISH_USER=
COOLEDAI_REDFISH_PASS=
COOLEDAI_FAIL_SAFE_PCT=70
COOLEDAI_VERIFY_SSL=1
ENVEOF

    echo "[OK]   Created $BACKEND_ENV"
    echo "       API Key:   ${API_KEY}"
    echo "       Admin Key: ${ADMIN_KEY}"
fi

echo ""

# --- Frontend .env.local ---
if [ -f "$FRONTEND_ENV" ]; then
    echo "[SKIP] $FRONTEND_ENV already exists."
    echo "       Delete it and re-run to regenerate, or edit manually."
else
    cat > "$FRONTEND_ENV" << ENVEOF
# =============================================================================
# CooledAI Frontend - Local Environment Variables
# =============================================================================
# Generated by setup_env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# NEVER commit real keys. This file is in .gitignore.
# =============================================================================

# Backend API URL (production)
NEXT_PUBLIC_API_URL=https://proactive-creativity-production.up.railway.app

# API Key for authenticated backend endpoints (must match COOLEDAI_API_KEY in .env)
# This is auto-populated from the backend key generated above.
NEXT_PUBLIC_COOLEDAI_API_KEY=${API_KEY}

# Clerk Authentication (get keys from https://dashboard.clerk.com)
# Leave as placeholders if using Demo Mode instead of Clerk.
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_REPLACE_ME
CLERK_SECRET_KEY=sk_test_REPLACE_ME

NEXT_PUBLIC_CLERK_SIGN_IN_URL=/portal/login
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up

# Demo Mode credentials (portal login without Clerk)
# Override these in production or disable demo mode entirely.
NEXT_PUBLIC_DEMO_USER=demo
NEXT_PUBLIC_DEMO_PASS=cooledai2026

# Lemon Squeezy (billing)
NEXT_PUBLIC_VARIANT_ID=your-variant-id
# NEXT_PUBLIC_LEMON_SQUEEZY_CHECKOUT_DOMAIN=billing.cooledai.com
# NEXT_PUBLIC_CHECKOUT_SUCCESS_REDIRECT_URL=https://www.cooledai.com/portal?success=true
ENVEOF

    echo "[OK]   Created $FRONTEND_ENV"
fi

echo ""
echo "=================================================="
echo "  Next Steps"
echo "=================================================="
echo ""
echo "  1. Review and fill in real values in:"
echo "     - $BACKEND_ENV"
echo "     - $FRONTEND_ENV"
echo ""
echo "  2. Start the backend (dev mode):"
echo "     source .env && python3 -m uvicorn api.main:app --reload"
echo ""
echo "  3. Start the frontend:"
echo "     cd frontend && npm run dev"
echo ""
echo "  4. The API key is required for control endpoints."
echo "     Pass it via: curl -H 'X-API-Key: YOUR_KEY' ..."
echo ""
echo "  5. /health is unauthenticated (used by watchdog sidecar"
echo "     and load balancers)."
echo ""
echo "  6. Rotate keys before production deployment."
echo ""
echo "=================================================="
